// Dữ liệu sản phẩm tách riêng ra khỏi index.html
const productData = [
  {
    title: "Nike Air Force 1 '07 LV8",
    price: 3519000,
    brand: "nike",
    image: "img/Nike Air Force 1 '07 LV8.avif",
  },
  {
    title: "Adidas Samba OG",
    price: 2700000,
    brand: "adidas",
    image: "img/Adidas Samba OG.avif",
  },
  {
    title: "New Balance NB 480 ‘Blue’",
    price: 2290000,
    brand: "balance",
    image: "img/New Balance NB 480 ‘Blue’.jpg",
  },
  {
    title: "Air Jordan 1 Low SE",
    price: 3239000,
    brand: "nike",
    image: "img/Air Jordan 1 Low SE.avif",
  },
  {
    title: "Adidas FORUM LOW CL",
    price: 2600000,
    brand: "adidas",
    image: "img/Adidas FORUM LOW CL.avif",
  },
  {
    title: "New Balance 475 ‘Quarry Blue’",
    price: 2399000,
    brand: "balance",
    image: "img/New Balance 475 ‘Quarry Blue’.jpg",
  },
  {
    title: "Nike Dunk Low Retro",
    price: 2343199,
    brand: "nike",
    image: "img/Nike Dunk Low Retro.avif",
  },
  {
    title: "Adidas Gazelle",
    price: 1875000,
    brand: "adidas",
    image: "img/Adidas Gazelle.avif",
  },
  {
    title: "New Balance 2002R ‘Incense’",
    price: 4899000,
    brand: "balance",
    image: "img/New Balance 2002R ‘Incense’.jpg",
  },
  {
    title: "Nike Cortez Leather",
    price: 2499000,
    brand: "nike",
    image: "img/Nike Cortez Leather.avif",
  },
  {
    title: "Adidas Superstar II",
    price: 2600000,
    brand: "adidas",
    image: "img/Adidas Superstar II.avif",
  },
  {
    title: "New Balance 2002R ‘Phantom’",
    price: 3290000,
    brand: "balance",
    image: "img/New Balance 2002R ‘Phantom’.jpg",
  },
  {
    title: "Nike Air Max Dn",
    price: 4999000,
    brand: "nike",
    image: "img/Nike Air Max Dn.avif",
  },
  {
    title: "Adidas Drop Step Low 2.0",
    price: 1900000,
    brand: "adidas",
    image: "img/Adidas Drop Step Low 2.0.avif",
  },
  {
    title: "New Balance 327 Infield Clay Copper",
    price: 2899000,
    brand: "balance",
    image: "img/New Balance 327 Infield Clay Copper.jpg",
  },
  {
    title: "Nike P-6000 Fade",
    price: 3239000,
    brand: "nike",
    image: "img/Nike P-6000 Fade.avif",
  },
  {
    title: "Adidas Campus 2.0",
    price: 2000000,
    brand: "adidas",
    image: "img/Adidas Campus 2.0.avif",
  },
  {
    title: "New Balance 5740 ‘Grey Red’",
    price: 4290000,
    brand: "balance",
    image: "img/New Balance 5740 ‘Grey Red’.webp",
  },
  {
    title: "Nike Metcon 10",
    price: 4409000,
    brand: "nike",
    image: "img/Nike Metcon 10.avif",
  },
  {
    title: "Adidas Handball Spezial",
    price: 2500000,
    brand: "adidas",
    image: "img/Adidas Handball Spezial.avif",
  },
  {
    title: "New Balance Refined Future Navy Grey",
    price: 4890000,
    brand: "balance",
    image: "img/New Balance Refined Future Navy Grey.jpg",
  },
  {
    title: "Nike Blazer Mid '77 Vintage",
    price: 2929000,
    brand: "nike",
    image: "img/Nike Blazer Mid '77 Vintage.avif",
  },
  {
    title: "Adidas Stan Smith Consortium",
    price: 2900000,
    brand: "adidas",
    image: "img/ADIDAS STAN SMITH CONSORTIUM.avif",
  },
  {
    title: "New Balance 1906R ‘White Green’",
    price: 4990000,
    brand: "balance",
    image: "img/New Balance 1906R ‘White Green’.webp",
  },
];
